capprojo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('chemoapp.urls')),
]

chemoapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from . import views, patient, trimester, doctor, forum,models

urlpatterns = [
     # -- authentication views
    url(r'^$', views.home, name='home'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^verify_doctor/$', views.verify_doctor, name='verify_doctor'),
    url(r'^signup_doctor/$', views.signup_doctor, name='signup_doctor'),
    url(r'^book_appointment/$', views.book_appointment, name='book_appointment'),

  
  # -- general views
    url(r'^search_doctors/$', views.search_doctors, name='search_doctors'),
    url(r'^individual_doctors_page/(\d+)/(\w+)/$', views.individual_doctors_page,
        name='individual_doctors_page'),

     # -- patient views
    url(r'^edit_patient_profile/$', patient.profile_edit,
        name='edit_patient_profile'),
    url(r'^antenatal/$', patient.antenatal, name='antenatal'),
    url(r'^patient_profile/(\d+)/(\w+)$',
        patient.patient_profile, name='patient_profile'),



    # -- doctors views
    url(r'^doctors_dashboard/$', doctor.dashboard, name='doctors_dashboard'),
    url(r'^doctor_profile/(\d+)/([A-Z|a-z\W\s]*)/$',
        doctor.doctor_profile, name='doctor_profile'),



    # --trimester views
    url(r'^due/$', patient.due, name='due'),
    url(r'^trimester1/$', trimester.trimester1,
        name='trimester1'),
    url(r'^trimester2/$', trimester.trimester2,
        name='trimester2'),
    url(r'^trimester3/$', trimester.trimester3,
        name='trimester3'),
    url(r'^scrollytelling/$', trimester.scrollytelling,
        name='scrollytelling'),

    # ---forum views
    url(r'^blogpost/$', forum.create_post, name='create_post'),
    url(r'^comment/', forum.add_comment, name='comment'),
    url(r'^forum/$', forum.forum, name='forum'),
    url(r'^forum/single_blog/(\d+)', forum.single_blog, name='single_blog'),
    
    url(r'^type',views.add_cancer,name='add_cancer'),
    url(r'^illness',views.cervical,name='cervical')

    


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

chemoapp/models.py
# still not sure what this does.Do more research after lunch
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.contrib.auth.models import User, AbstractBaseUser
from django.contrib import admin
from django.db import models
from django import forms
from datetime import datetime
from datetime import date, datetime
from django.utils import timezone
import numpy as np
import pandas as pd
from itertools import groupby
from django.shortcuts import render, redirect

TIME_CHOICES = (
    ('6', '6:00 am'),
    ('7', '7:00 am'),
    ('8', '8:00 am'),
    ('9', '9:00 am'),
    ('10', '10:00 am'),
    ('11', '11:00 am'),
    ('12', '12:00 am'),
    ('13', '1:00 pm'),
    ('14', '2:00 pm'),
    ('15', '3:00 pm'),
    ('16', '4:00 pm'),
    ('17', '5:00 pm'),
    ('18', '6:00 pm'),
)


days = ['Monday', 'Tuesday', 'Wednesday',
        'Thursday', 'Friday', 'Saturday', 'Sunday']
# -- Location


class Location(models.Model):
    location = models.CharField(max_length=50)

    def delete_location(self):
        return self.delete()

    def __str__(self):
        return self.location


class LocationAdmin(admin.ModelAdmin):
    search_fields = ('location',)


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        exclude = []
        fields = ()


# -- Doctor model to display everything about the doctor and what services he or she offers and what time they are available for an appointment


class DoctorSpeciality(models.Model):
    specialty = models.CharField(max_length=30, primary_key=True)

    def __str__(self):
        return self.specialty

    class Meta:
        verbose_name_plural = 'Doctors specialties'


class DoctorSpecialityAdmin(admin.ModelAdmin):
    search_fields = ('specialty', )


class DoctorSpecialityForm(forms.ModelForm):
    class Meta:
        model = DoctorSpeciality
        exclude = []


class Doctor(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    photo = models.FileField(
        upload_to='images', default='default.jpg', null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    specialty = models.ForeignKey(DoctorSpeciality, null=True)
    consultation_fee = models.FloatField(default=0, null=True)

    @classmethod
    def create_doctor(cls, user, fee):
        cls.objects.create(user=user, consultation_fee=fee)

    def make_appointments(self):
        days = pd.date_range('2012-05-25', '2012-06-27', freq='D')
        appointments = []
        for day in days:
            app = Appointment.objects.create(doctor=self, day=day)
            appointments.append(app)
        return appointments

    @property
    def booked_slots(self):
        apps = list(self.appointments.all().order_by('day'))
        objects = []
        for k, v in groupby(apps, lambda x: x.day):
            objects.append(list(v))
        return objects

    @property
    def booked_days(self):
        apps = list(self.appointments.all().order_by('day'))
        ls = []
        for k, v in groupby(apps, lambda x: x.day):
            ls.append(k)
        return ls

    @property
    def all_appointments(self):
        return self.appointments.all().order_by('day')

    @property
    def full_name(self):
        return f'Dr.{self.first_name.capitalize()} {self.last_name.capitalize()}'

    @classmethod
    def search_doctors_by_term(cls, search_term):
        by_first_name = cls.objects.filter(first_name__icontains=search_term)
        by_last_name = cls.objects.filter(last_name__icontains=search_term)
        search_results = list(by_first_name) + list(by_last_name)
        return search_results

    @classmethod
    def get_one_doctor(cls, doctor_id):
        user = User.objects.get(pk=doctor_id)
        return cls.objects.get(pk=user)

    @classmethod
    def get_all_doctors(cls):
        return cls.objects.all()

    def patients(self):
        return Patient.doctor_patients(self)

    def delete_doctor(self):
        self.delete()

    def average_service(self):
        service_ratings = list(
            map(lambda x: x.service_rating, self.reviews.all()))
        return np.mean(service_ratings)

    def average_professionalism(self):
        professionalism_ratings = list(
            map(lambda x: x.professionalism_rating, self.reviews.all()))
        return np.mean(professionalism_ratings)

    def average_friendliness(self):
        friendliness_ratings = list(
            map(lambda x: x.friendliness_rating, self.reviews.all()))
        return np.mean(friendliness_ratings)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        exclude = ['user']


class DoctorAdmin(admin.ModelAdmin):
    raw_id_fields = ('user',)
    list_display = ('first_name', 'last_name', )
    list_filter = ('specialty',)
    list_display = ('__str__', 'specialty',)

# --


class DoctorProfile(models.Model):
    doctor = models.OneToOneField(
        Doctor, on_delete=models.CASCADE, related_name='profile')
    name = models.CharField(max_length=100)
    score = models.IntegerField(default=0)
    registration_number = models.CharField(max_length=100)
    registration_date = models.CharField(max_length=100)
    nationality = models.CharField(max_length=100)
    facility = models.CharField(max_length=100)
    postal_address = models.CharField(max_length=100)
    speciality = models.CharField(max_length=100)
    sub_speciality = models.CharField(max_length=100)
    qualifications = models.CharField(max_length=100)


class DoctorProfileForm(forms.ModelForm):
    class Meta:
        model = DoctorProfile
        exclude = ['doctor']


# --

class DoctorWorkingHours(models.Model):
    doctor = models.OneToOneField(
        Doctor, on_delete=models.CASCADE, related_name='working_hours')
    working_from = models.CharField(max_length=20, choices=TIME_CHOICES)
    working_to = models.CharField(max_length=20, choices=TIME_CHOICES)

    @property
    def appointment_slots(self):
        start = self.working_from
        end = self.working_to
        ls = list(range(int(start), int(end)))
        dc = {6: '6:00 am', 7: '7:00 am', 8: '8:00 am', 9: '9:00 am', 10: '10:00 am', 11: '11:00 am',
              12: '12:00 am', 13: '1:00 pm', 14: '2:00 pm', 15: '3:00 pm', 16: '4:00 pm', 17: '5:00 pm', 18: '6:00 pm'}
        slots = []
        for i in ls:
            slots.append(dc.get(i))
        return slots

    def __str__(self):
        return f'from-{self.working_from} to-{self.working_to}'


class DoctorWorkingHoursForm(forms.ModelForm):
    class Meta:
        model = DoctorWorkingHours
        exclude = ['doctor']

    def save(self, doctor, commit=True):
        hours = super(DoctorWorkingHoursForm, self).save(commit=False)
        hours.doctor = doctor
        hours.save()


class DoctorWorkingHoursAdmin(admin.ModelAdmin):
    list_display = ('doctor', 'working_from', 'working_to',)


# Patient model that displays all the patient details and what he/ she might be wanting to have a look at


class Patient(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    photo = models.FileField(
        upload_to='images', default='default.jpg', null=True)
    doctors = models.ManyToManyField(Doctor)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    id_number = models.CharField(max_length=8, unique=True)
    birthday = models.DateField()
    location = models.ForeignKey(Location)

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)

    @classmethod
    def doctor_patients(cls, doctor):
        return cls.objects.filter(doctor=doctor)

    @classmethod
    def get_patient(cls, pt):
        return cls.objects.get(user=pt)

    def save_patient(self, user):
        self.user = user
        self.save()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class PatientAdmin(admin.ModelAdmin):
    raw_id_fields = ('user',)
    search_fields = ('first_name', 'last_name', 'id_number')
    list_display = ('__str__', 'birthday', 'id_number', )


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        exclude = ['user', 'doctors']

# --


class Appointment(models.Model):
    doctor = models.ForeignKey(
        Doctor, on_delete=models.CASCADE, related_name='appointments', null=True)
    day = models.DateField()
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    time_slot = models.CharField(
        max_length=20, choices=TIME_CHOICES, null=True)
    is_booked = models.BooleanField(default=False)
    is_completed = models.BooleanField(default=False)

    @property
    def complete_appointment(self):
        self.is_completed = True
        self.save()

    @classmethod
    def book_appointment(cls, appointment, doctor, patient):
        # appointment = cls.objects.get(appointment_id)
        appointment.doctor = doctor
        appointment.patient = patient
        appointment.booked = True
        appointment.save()

    def __str__(self):
        return f'{self.doctor} {self.patient} {self.time_slot}'


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        exclude = ['doctor', 'patient', ]


class AppointmentAdmin(admin.ModelAdmin):
    list_display = ('doctor', 'day', 'patient', 'time_slot',
                    'is_booked', 'is_completed',)


# --


class AppointmentDetails(models.Model):
    appointment = models.ForeignKey(
        Appointment, on_delete=models.CASCADE, related_name='details')
    notes = models.TextField()


class AppointmentDetailsForm(forms.ModelForm):
    class Meta:
        model = AppointmentDetails
        exclude = ['appointment']


class AppointmentDetailsAdmin(admin.ModelAdmin):

chemoapp/forms.py
from django import forms
# fill in custom user info then save it
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.contrib.admin.widgets import AdminDateWidget, AdminTimeWidget
from django.forms.fields import DateField


class MyRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(MyRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        user.save()

        return user


class DoctorRegistrationForm(UserCreationForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField(required=True)
    reg_no = forms.CharField(required=False)
    fee = forms.IntegerField(required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(DoctorRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.consultation_fee = self.cleaned_data['fee']
        reg_no = self.cleaned_data['reg_no']

        user.save()

        return user


class SearchDoctorsForm(forms.Form):
    search_term = forms.CharField(max_length=50)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ['poster', 'date']


class PostForm(forms.ModelForm):
    class Meta:
        model = Posts
        exclude = ['posted_by']


class CheckDoctorsForm(forms.Form):
    check_doctor = forms.CharField(max_length=50)


class CancerForm(forms.ModelForm):
    class Meta:
        model = Cancer
        fields =['illness']

chemoapp/templates/cancer.html
{%extends "base/base.html"%}
{% load bootstrap4 %}
{%load static%}
{% block content %}
<div class="container">


    <div class="row">

            <div class="col-md-2 col-sm-1 "></div>
            <div class="col-md-8 col-sm-10 col-xs-12">

                <div class="card">

                    <div class="card-header" style="font-size:20px">
                        Type of illness
                    </div>

                    <div class="card-body">
                            <form style="border:white" action="{% url 'add_cancer'    %}" method="post" enctype="multipart/form-data">
                                {%csrf_token%}
                                {% bootstrap_form form%}
                                <input type="submit" class="btn btn-primary btn-sm" value="Post">
                            </form>

                    </div>
                </div>

    </div>
</div>



 
{%endblock%}

chemoapp/templates/doctor_page.html
{%extends "base/base.html"%}

{% load bootstrap4 %}

{%load static%}

{% block content %}

<h2>{{ doctor.user.username }}</h2>

<!-- <h5>{{ doctor.review_set.count }} reviews ({{ project.service_rating | floatformat }} average rating of doctor's client
    service </h5>
<h5>{{ doctor.review_set.count }} reviews ({{ project.professionalism_rating | floatformat }} average rating of
    professionalism</h5>
<h5>{{ doctor.review_set.count }} reviews ({{ project.friendliness_rating | floatformat }} average rating of
    friendliness</h5> -->


<h3>See what other patients have to say about this doctor</h3>

{% if doctor.review_set.all %}

<div class="row">
    {% for review in doctor.review_set.all %}
    <div class="col-xs-6 col-lg-4">
        <em>{{ review.comment }}</em>
        <h6>Service Rated {{ review.service_rating}} of 10 by {{ review.user }}</h6>
        <h6>Professionalism Rated {{ review.professionalism_rating }} of 10 by {{ review.user }}</h6>
        <h6>Friendliness Rated {{ review.friendliness_rating }} of 10 by {{ review.user }}</h6>
    </div>
    {% endfor %}
</div>

{% endif %}

{% endblock %}

chemoapp/templates/doctors_search.html
{%extends "base/base.html"%}

{% load bootstrap4 %}

{%load static%}

{% block content %}
<section id="search-header">
    <div class="vh-80 bg-dark-blue">
        <div class="container h-100">
            <div class="w-50 h-100 bg-dark-aqua d-flex float-right text-sea px-5">
                <div class="my-auto">
                    <h5 class="text-white-50">Amama for expectant women</h5>
                    <h1 class="display-4">Help is just an appointment away!</h1>
                    <p class="pl-2 py-3">
                        Find the perfect health proffessional for you to guide you through you pregnancy journey. All
                        our
                        practitioners have been veted and approved by the medical board. What are you waiting for?
                    </p>
                    <a href="#id_search_term">
                        <label class="btn bg-dark-blue text-sea" for="id_search_term">Find a proffessional</label>
                    </a>
                </div>
            </div>
            <div class="w-50">
                <img class="h-100 img-fluid" src="{% static 'img/black-doctor.png' %}" alt="">
            </div>
        </div>
    </div>
</section>


<section id="search-doctors-section">
    <div class="my-5 d-flex flex-column">
        <div class="container d-flex my-3">
            <form action="/search_doctors/#id_search_term" method="GET">
                <div class="d-flex">
                    <input class="form-control w-auto" type="text" name="search_term" maxlength="50" required id="id_search_term"
                        placeholder="Who are you looking for?" />
                    <button class="btn btn-info ml-3 px-4" type="submit">search</button>
                </div>
            </form>
            {% if searched_doctors %}
            <h2 class="ml-4">
                {{searched_doctors | length }} Doctor(s) Found</h2>
            {% endif %}

            {% if searched_doctors.count is 0 %}
            <h2 class="ml-4"> It appears that there are 0 doctors for your search term
                {{message}}, please try again. </h2>
            {% endif %}
        </div>
        <div class="search_results container">
            <div class="row mx-0 my-3">
                {% for doctor in searched_doctors %}
                <div class="col-md-3 text-center my-3">
                    <div class="">
                        <img class="w-100 rounded-circle" src="{{doctor.photo.url}}" data-target="#imageModal{{doctor.id}}"
                            data-toggle="modal" alt="" class="img-fluid" id="eachimage">
                    </div>
                    <a href="{% url 'doctor_profile' doctor.user.id doctor.full_name %}">
                        <h3 class="my-2">{{ doctor.full_name }}</h3>
                    </a>
                    <h5 class="mb-3">{{ doctor.consultation_fee }}
                        <span class="ml-2">Ksh</span>
                    </h5>
                    <a href="#doctor{{ doctor.user.id }}">
                        <button onclick="showBooking('{{ doctor.user.id }}')" class="btn bg-dark-blue text-aqua">Book
                            an
                            appointment</button>
                    </a>
                </div>

                <div class="d-none calendars" id="doctor{{ doctor.user.id }}">
                    <div class="d-flex my-2 mr-auto" id="calendaer-booking">
                        <div class="w-75 mx-auto">
                            <h3>Choose Day</h3>
                            <div class="d-flex">
                                {% include 'includes/patient_calendar.html' %}
                            </div>
                        </div>

                        <div class="w-25">
                            <h3>Choose Time</h3>
                            <div class="d-flex flex-wrap">
                                {% for slot in doctor.working_hours.appointment_slots %}
                            
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
</section>


<section>
    {% for doctor in doctors %}
    <div class="my-5">
        <div class="d-flex container text-center">
            <div class="profile-photo">
                <img class="rounded-circle" src="{{ doctor.photo.url }}" alt="">
            </div>
            <a class="text-dark-blue decoration-none" href="/doctor_profile/{{doctor.user.id}}/{{doctor.full_name}}/">
                <h3 class="my-2">{{ doctor.full_name }}</h3>
                <div>
                    <h5>
                        <span>Consultation fee: ksh </span>
                        <span>{{ doctor.consultation_fee }}</span>
                    </h5>
                </div>
            </a>
        </div>

        <div class="d-none">
            <div>
                <h3>Book an appointment</h3>
            </div>

            <div class="w-75 mx-auto">
                <h5>Choose Day</h5>
                <div class="d-flex">
                    {% include 'includes/patient_calendar.html' %}
                </div>
            </div>

            <div class="w-25">

                <h5>Choose Time</h5>
                <div class="d-flex flex-wrap">

                    {% for slot in doctor.working_hours.appointment_slots %}
                    <div class="m-1">
                        <button class="slot-width btn cbody" id="{{ slot }}" onclick="setSlot(this.id); $('#submit-book-btn').click()">
                            <span>
                                {{ slot }}
                            </span>
                        </button>
                    </div>
                    {% endfor %}

                </div>

            </div>
        </div>
    </div>
    {% endfor %}
</section>




<section id="how-works">
    <div class="container">
        <div class="text-center my-5">
            <h2>How it Works</h2>
        </div>
        <div class="px-5 d-flex">
            <div class="w-50">
                <img src="{% static 'img/how-it-works.png' %}" alt="">
            </div>
            <div class="w-50">
                <div class="mb-5">
                    <h5 class="font-weight-bold">1. Register For Free</h5>
                    <p>
                        Signing up with us is a very quick process. Just click <a class="text-aqua" href="{% url 'signup' %}">here</a>
                        and you will be done in a minute!
                    </p>
                </div>
                <div class="mb-5">
                    <h5 class="font-weight-bold">1. Register For Free</h5>
                    <p>
                        Signing up with us is a very quick process. Just click <a class="text-aqua" href="{% url 'signup' %}">here</a>
                        and you will be done in a minute!
                    </p>
                </div>
                <div class="mb-5">
                    <h5 class="font-weight-bold">1. Register For Free</h5>
                    <p>
                        Signing up with us is a very quick process. Just click <a class="text-aqua" href="{% url 'signup' %}">here</a>
                        and you will be done in a minute!
                    </p>
                </div>
                <div class="mb-5">
                    <h5 class="font-weight-bold">1. Register For Free</h5>
                    <p>
                        Signing up with us is a very quick process. Just click <a class="text-aqua" href="{% url 'signup' %}">here</a>
                        and you will be done in a minute!
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container d-flex border-bottom">
        <h1 class="">Top Rated Doctors</h1>
        <div class="filter-doctors ml-auto d-flex align-items-center">
            <p class="ml-3 mb-0">Filter</p>
            <button class="ml-3 my-2 btn btn-sm ">Location</button>
            <button class="ml-3 my-2 btn btn-sm active">Ratings</button>
            <button class="ml-3 my-2 btn btn-sm ">Price</button>
        </div>
    </div>
</section>

<section>
    {% for doctor in doctors %}
    <div class="my-5">
        <div class="d-flex container">
            <div class="profile-photo">
                <img class="rounded-circle" src="{{ doctor.photo.url }}" alt="">
            </div>
            <div class="d-flex align-items-center">

                <a href="/doctor_profile/{{doctor.user.id}}/{{doctor.full_name}}/">
                    <h3 class="my-2">{{ doctor.full_name }}</h3>
                </a>
            </div>
        </div>

        <div class="d-none">
            <div>
                <h3>Book an appointment</h3>
            </div>

            <div class="w-75 mx-auto">
                <h5>Choose Day</h5>
                <div class="d-flex">
                    {% include 'includes/patient_calendar.html' %}
                </div>
            </div>

            <div class="w-25">

                <h5>Choose Time</h5>
                <div class="d-flex flex-wrap">

                    {% for slot in doctor.working_hours.appointment_slots %}
                    <div class="m-1">
                        <button class="slot-width btn cbody" id="{{ slot }}" onclick="setSlot(this.id); $('#submit-book-btn').click()">
                            <span>
                                {{ slot }}
                            </span>
                        </button>
                    </div>
                    {% endfor %}

                </div>

            </div>
        </div>
    </div>
    {% endfor %}
</section>

<!-- form for submiting an appointment booking -->
<form action="" method="POST" id="book-form" data-url="http://localhost:8000/search_doctors/">
    <input class="d-none" type="date" name="day" required id="id_day" />
    <input class="d-none" type="text" name="time_slot" required id="id_time_slot" />

    <button class="d-none" id="submit-book-btn" type="submit">book</button>
</form>
<!-- form for submiting an appointment booking -->


</div>

</div>


</div>



<!--modal-->
{% for image in pictures %}
<div class="modal fade" id="imageModal{{doctor.id}}" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <img src="{{doctor.image.url}}" data-toggle="modal" alt="" style="height:600px;width:500px;">
            <div class="modal-header">
                <h4 id="modal-text text-center">{{doctor.name}}</h4>
                <h4 style="font-family: 'Kodchasan', sans-serif;color:blue;" id="modal-text ">{{doctor.location}}</h4>

            </div>

            <div class="modal-footer">

                <input class="form-control" type="text" value="https://linkedin.com{{doctor.image.url}}">
                <button type="button" value="https://linkedin.com{{doctor.image.url}}" onclick="copyLink(this.value)"
                    class="btn btn-outline-secondary my-2 my-0 link-btn">Copy
                    Photo Link</button>

            </div>
            <div class="modal-footer">

                <h5 id=modal-text>{{doctor.name}}</h5>

                <button type="button" class="btn btn-outline-secondary
              my-2 my-sm-0" data-dismiss="modal">Close</button>

            </div>
        </div>
    </div>
</div>


{% endfor %}

{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="{% static 'js/calendar.js' %}" charset="utf-8"></script>
{% endblock %}

chemoapp/templates/placeholders.html
<div class="form-group">
    <div class="my-3 field d-flex">
            {{ form.first_name.errors }}
            <input class="border-dark-blue opacity-7 form-control py-4 mr-2" type="text" name="first_name" id="id_first_name"
                    required placeholder="Enter your first name" />
            {{ form.last_name.errors }}
            <input class="border-dark-blue opacity-7 form-control py-4" type="text" name="last_name" id="id_last_name"
                    required placeholder="Enter your last name" />
    </div>
    <div class="my-3 field d-flex">
            {{ form.username.errors }}
            <input class="border-dark-blue opacity-7 form-control py-4 mr-2" type="text" name="username" id="id_username"
                    required placeholder="Enter your username" />
            {{ form.email.errors }}
            <input class="border-dark-blue opacity-7 form-control py-4" type="text" name="email" id="id_email"
                    required placeholder="Enter your email" />
    </div>
    <div class="my-3 field d-flex">
            {{ form.password1.errors }}
            <input class="border-dark-blue opacity-7 form-control py-4 mr-2" type="password" name="password1" id="id_password1"
                    required placeholder="Enter new password" />
            {{ form.password2.errors }}
            <input class="border-dark-blue opacity-7 form-control py-4" type="password" name="password2" id="id_password2"
                    required placeholder="Confirm password" />
    </div>
    <div class="my-3 field d-flex">
            <label class="border-dark-blue opacity-0 form-control py-4 mr-2" for="id_fee">Fee:</label>
            {{ form.fee.errors }}
            <input class="border-dark-blue opacity-7 form-control py-4" type="password" name="fee" id="id_fee"
                    required placeholder="ksh" />
    </div>
</div>

<p><label for="id_username">Username:</label> <input type="text" name="username" maxlength="150" autofocus required id="id_username" />
    <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span></p>
<p><label for="id_email">Email:</label> <input type="email" name="email" required id="id_email" /></p>
<p><label for="id_password1">Password:</label> <input type="password" name="password1" required id="id_password1" />
    <span class="helptext">
            <ul>
                    <li>Your password can&#39;t be too similar to your other personal information.</li>
                    <li>Your password must contain at least 8 characters.</li>
                    <li>Your password can&#39;t be a commonly used password.</li>
                    <li>Your password can&#39;t be entirely numeric.</li>
            </ul>
    </span></p>
<p><label for="id_password2">Password confirmation:</label> <input type="password" name="password2" required id="id_password2" />
    <span class="helptext">Enter the same password as before, for verification.</span></p>
<p><label for="id_first_name">First name:</label> <input type="text" name="first_name" id="id_first_name" /></p>
<p><label for="id_last_name">Last name:</label> <input type="text" name="last_name" id="id_last_name" /></p>
<p><label for="id_reg_no">Reg no:</label> <input type="text" name="reg_no" id="id_reg_no" /></p>
<p><label for="id_fee">Fee:</label> <input type="number" name="fee" id="id_fee" /></p>